SQLALCHEMY_DATABASE_URI = "mysql+pymysql://root:password@localhost/dsi_clone"
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = "sosisadam"
AUTO_CREATE_SCHEMA = True
RESET_SCHEMA_ON_EACH_LAUNCH = True
RESET_COOKIE_ON_EACH_LAUNCH = False
FILL_MOCK_DATA = True